### ISSUE TITLE
how the addr and data width is getting set

### ISSUE THREAD

**Issue by psumesh** [aignacio/cocotbext-ahb#6]
Hi,

I am a beginner at integrating the AHB, and want to know how the addr and data width are getting set in 

```
    @property
    def data_width(self):
        return self._data_width

    @property
    def addr_width(self):
        return self._addr_width
```

I got an error : 
self._data_width = len(self.hwdata) 
TypeError: object of type 'NoneType' has no len()

for my custom requirement, address width is 64 and data width is 32. appreciated if you can give an example.

**Comment by aignacio** [comment]
Hey @psumesh,

the attribute `hwdata` of the class `AHBBus` is an extension of the base class `Bus`. It'll get initialized through the code below which is a call to the __init__ method of the parent class (or superclass) of the current class. Your error could be related to the fact that the base class `Bus` could not map / find correctly the hwdata. Can you share how did you instantiate the objects?

https://github.com/aignacio/cocotbext-ahb/blob/0a871515f5837eb6aa356e859c4d7a7d36498f03/cocotbext/ahb/ahb_bus.py#L57

A simple example of your dut as a slave AHB:
```python
    ...
   
    # Create an AHB Lite Master connected to the slave I/F
    # assume your dut AHB signals are prefixed with slave_
    ahb_lite_master = AHBLiteMaster(
        AHBBus.from_prefix(dut, "slave"), dut.hclk, dut.hresetn, def_val=0
    )
   
    bit _addr = 64 # 64-bit address
    bit _data = 32 # 32-bit bus data
    address = random.randint(0, (2**bit_addr) - 1)
    value = random.randint(0, (2**bit_data) - 1)
    size = 4 # 4-bytes / 32-bit data

    # Perform the writes and reads
    resp = await ahb_lite_master.write(address, value, size)
    resp = await ahb_lite_master.read(address, size)
```

**Comment by psumesh** [comment]
Hi @aignacio 
Thank you for the prompt response with example. it served the purpose perfectly! I appreciate your help.
